volumes:
  docker_lab_pgdata:
  models:
  data:

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    ports:
      - "55332:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      TZ: Asia/Tokyo
    restart: always
    healthcheck:
      test:
        ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -l || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - docker_lab_pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf # JST用設定ファイルをマウント

  # ネイティブOllamaを使用するためDocker Ollamaサービスを削除
  # ホストのOllamaサービスをhttp://host.docker.internal:11434で使用
  frontend:
    build: ./frontend
    container_name: rag_frontend
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - TZ=Asia/Tokyo
    depends_on:
      - db
      - backend
    restart: always
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env  # .envファイルをマウント
      - models:/app/models  # モデルの永続化

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # ビルド時の引数を設定
      args:
        - PYTHONUNBUFFERED=1
        - PIP_CACHE_DIR=/root/.cache/pip
    image: rag_backend_debug
    container_name: rag_backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRANSFORMERS_CACHE=/app/.cache/huggingface/hub
      - HF_HOME=/app/.cache/huggingface
      - TORCH_HOME=/app/.cache/torch
      - TZ=Asia/Tokyo
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      # モデルキャッシュを永続化
      - models:/app/.cache
      # ローカルHuggingFaceモデルをマウント（GPU加速用）
      - ./local_models:/app/local_models
      # アプリケーションコードのホットリロード用（開発時のみ）
      - ./backend/app:/app/app
      - ./backend/models.yaml:/app/models.yaml
      - ./backend/strategies.yaml:/app/strategies.yaml
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
